---
# https://github.com/nodesource/distributions/blob/master/README.md

- name: Remove Chris Lea's Node.js PPA
  apt_repository:
    repo: 'ppa:chris-lea/node.js'
    state: absent

- name: Remove Chris Lea's Node.js PPA files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/apt/sources.list.d/chris-lea-node_js-*.list"
    - "/etc/apt/sources.list.d/chris-lea-node_js-*.list.save"

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - build-essential
    state: present

- name: Add NodeSource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present

- name: Add NodeSource apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"

- name: Install nodejs
  apt:
    name: "nodejs={{ nodejs_version }}*"
    state: present

- name: Install npm packages
  npm:
    name: "{{ (item.name | default(omit)) if item.path is defined else (item.name | default(item)) }}"
    version: "{{ item.version | default(omit) }}"
    global: "{{ omit if item.path is defined else (item.global | default('true')) }}"
    ignore_scripts: "{{ item.ignore_scripts | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    production: "{{ item.production | default(omit) }}"
    registry: "{{ item.registry | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ nodejs_install_packages }}"
